title: "Md Raqib Khan"
logo: "myimage.jpg"  # Make sure this file exists at the specified path
description: "Computer Science and Signal Processing Engineer"
theme: jekyll-theme-minimal
show_downloads: true  # Corrected typo here
url: "https://mdraqibkhan.github.io"
baseurl: ""  # Keep this empty unless your site is in a subdirectory
