title: Md Raqib Khan
logo: /assets/IMG_20241013_163550.jpg
description: Personal portfolio site for showcasing projects.
theme: jekyll-theme-minimal
show_dwnloads: true
url: "https://github.com/Mdraqibkhan/Mdraqibkhan.github.io"
baseurl: ""
