title: "Md Raqib Khan"
logo: "assest/unnamed.jpg"  # Adjust the path to where your image is stored
description: "Computer Science and Signal Processing Engineer"
theme: jekyll-theme-minimal
show_downloads: true
url: "https://mdraqibkhan.github.io"
baseurl: ""
